title: Godslove Mmesoma 
logo: mesh.jpeg
description: Data Analyst with 2+ years of experience, skilled in SQL, Excel, Power BI, statistical analysis, data visualization, and predictive modeling to support data-driven decision-making. 
#show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal

